### PR TITLE
Digital Domain 3.0, Inc. approved relicense from MPL-2.0 to Apache-2.0

### PR DESCRIPTION
**Pull request by plattfot**
Our approval is marked by the addition of our name to the RE-LICENSE_NOTE.txt.

### CODE REVIEW

**Comment by jmlait** [comment]
The DCO test is failing, which is a bit confusing to me as the commit appears to have been signed off properly?

**Comment by plattfot** [comment]
Could it be an issue with this is not being signed by the commit author (i.e. me)?

**Comment by plattfot** [comment]
Yeah, that was the issue. I just pushed a commit with me signing off the commit and not Deke.  I missed that the DCO must be signed off by the author.

**Review by jmlait — APPROVED** [review]

**Comment by jmlait** [comment]
Excellent, thank you, we can commit when we get a second TSC signoff.

**Review by apradhana — APPROVED** [review]

**Review by kmuseth — APPROVED** [review]

**Pull request merged**
