### PR TITLE
NodeUnion + Trivial Type changes (ABI=8)

### PR DESCRIPTION
**Pull request by Idclip**
This PR is based on the original type PR proposed here: https://github.com/AcademySoftwareFoundation/openvdb/pull/865. It was reverted here due to ABI issues: https://github.com/AcademySoftwareFoundation/openvdb/pull/895

ABI branching on the implementation of `NodeUnion` fixes some issues, but complete ABI branching on all changes is required. I have introduced ABI tests which fail without these. A by-product of these changes is that PointDataGrid topology memory footprint is reduced by 50%.

### CODE REVIEW

**Review by danrbailey — APPROVED** [review]
Looks good to me, thanks for adding the ABI test!

**Comment by Idclip** [comment]
I encountered yet another problem with `TypedAttributeArrays` templated on one of the container types (i.e. `Vec3f`). I added another ABI test for this which failed so have guarded every single constructor/copy/assignment operator for all the math types in `ABI >= 8`. This PR should no longer have any impact for any ABI versions other than 8.

**Comment by Idclip** [comment]
I should note that, because of this change, `PointDataGrid` topology now has half the memory footprint!

Before:
```
Information about Tree:
  Type: Tree_ptdataidx32_5_4_3
  Configuration:
    Root(1 x 8), Internal(8 x 32^3), Internal(8 x 16^3), Leaf(9 x 8^3)
  Background value: 0
  Min value: 1
  Max value: 1
  Number of active voxels:       9
  Number of active tiles:        0
  Bounding box of active voxels: [-100, -100, -100] -> [100, 100, 100]
  Dimensions of active voxels:   201 x 201 x 201
  Percentage of active voxels:   0.000111%
  Average leaf node fill ratio:  0.195%
  Number of unallocated nodes:   0 (0%)
Memory footprint:
  Actual:                4.593 MB
  Active leaf voxels:       36 Bytes
  Dense equivalent:     30.978 MB
  Actual footprint is 14.8% of an equivalent dense volume
  Leaf voxel footprint is 0.000747% of actual footprint
Transform:
  voxel size: 0.1
  index to world:
     [0.1, 0, 0, 0] 
     [0, 0.1, 0, 0] 
     [0, 0, 0.1, 0] 
     [0, 0, 0, 1] 
```

After:
```
Information about Tree:
  Type: Tree_ptdataidx32_5_4_3
  Configuration:
    Root(1 x 8), Internal(8 x 32^3), Internal(8 x 16^3), Leaf(9 x 8^3)
  Background value: 0
  Min value: 1
  Max value: 1
  Number of active voxels:       9
  Number of active tiles:        0
  Bounding box of active voxels: [-100, -100, -100] -> [100, 100, 100]
  Dimensions of active voxels:   201 x 201 x 201
  Percentage of active voxels:   0.000111%
  Average leaf node fill ratio:  0.195%
  Number of unallocated nodes:   0 (0%)
Memory footprint:
  Actual:                2.343 MB
  Active leaf voxels:       36 Bytes
  Dense equivalent:     30.978 MB
  Actual footprint is 7.56% of an equivalent dense volume
  Leaf voxel footprint is 0.00147% of actual footprint
Transform:
  voxel size: 0.1
  index to world:
     [0.1, 0, 0, 0] 
     [0, 0.1, 0, 0] 
     [0, 0, 0.1, 0] 
     [0, 0, 0, 1] 
```

**Comment by Idclip** [comment]
I did get a failure on my branch: https://github.com/Idclip/openvdb/runs/1595362883?check_suite_focus=true
Blosc related - @danrbailey any thoughts?

**Comment by danrbailey** [comment]
That does seem safer, thanks. I haven't seen that test fail recently and nothing stands out in the list of dependencies.

**Pull request merged**
