### PR TITLE
Changed the docs workflow to deploy to the website repo

### PR DESCRIPTION
**Pull request by Idclip**
Signed-off-by: Nick Avramoussis <4256455+Idclip@users.noreply.github.com>

### CODE REVIEW

**Comment by Idclip** [comment]
@danrbailey instructions for changing this are here:
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository

We can either use a personal access token or shh key:
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key

**Review by danrbailey — APPROVED** [review]

**Comment by danrbailey** [comment]
Think I've set up the public/private deploy keys correctly. I've merged this to a new feature/docs branch so that we can test it out.

**Comment by apradhana** [comment]
Thank you, @Idclip and @danrbailey!

**Comment by danrbailey** [comment]
Not sure what's going wrong here, something about this isn't working:

https://github.com/AcademySoftwareFoundation/openvdb/actions/runs/1478601024

**Comment by Idclip** [comment]
Which route did you use, ssh-key or personal access token? Seems that the `deploy-key` entry wants a ssh key (private key set on this repo, public on the website repo)

**Comment by danrbailey** [comment]
> Which route did you use, ssh-key or personal access token? Seems that the `deploy-key` entry wants a ssh key (private key set on this repo, public on the website repo)

That's right, that's what I tried. I created an ssh private/public key pair, added the public key as a deploy key to the website repo and the private key as a secret variable to this repo called `ACTIONS_DEPLOY_KEY`.

**Pull request merged**
