### PR TITLE
Use private key for Houdini password

### PR DESCRIPTION
**Pull request by danrbailey**

### CODE REVIEW

**Comment by danrbailey** [comment]
@pcucka @Idclip @jmlait @kmuseth - can someone approve this please?

It's a simple change, moving the plaintext password up into a CI env variable, but it's needed for one of the CII best practices badge criteria.

**Comment by Idclip** [comment]
> It's a simple change, moving the plaintext password up into a CI env variable, but it's needed for one of the CII best practices badge criteria.

So where's this password now stored, in Circles config? How would we change it if required?

**Comment by danrbailey** [comment]
> > It's a simple change, moving the plaintext password up into a CI env variable, but it's needed for one of the CII best practices badge criteria.
> 
> So where's this password now stored, in Circles config? How would we change it if required?

Yes, I added it to our Circle CI config, as I have administrator privileges. For Azure, we'd need to contact the ASWF helpdesk to do it for us.

**Comment by Idclip** [comment]
> Yes, I added it to our Circle CI config, as I have administrator privileges. For Azure, we'd need to contact the ASWF helpdesk to do it for us.

cool thanks for clarifying

**Pull request merged**
