### PR TITLE
Fixes for tbb::atomic errors reported by GCC 6.3

### PR DESCRIPTION
**Pull request by pcucka**
With the combination of GCC 6.3 and TBB 4.4.6 (not one of the VFX platform configurations), I'm getting errors like this:
```
openvdb/tree/LeafBuffer.h:254:19: error: no matching function for call to ‘tbb::atomic<unsigned int>::atomic(int)’
     , mOutOfCore(0)
                   ^
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note: candidate: tbb::atomic<unsigned int>::atomic()
 __TBB_DECL_ATOMIC(unsigned)
 ^
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note:   candidate expects 0 arguments, 1 provided
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note: candidate: constexpr tbb::atomic<unsigned int>::atomic(const tbb::atomic<unsigned int>&)
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note:   no known conversion for argument 1 from ‘int’ to ‘const tbb::atomic<unsigned int>&’


In file included from openvdb/points/AttributeGroup.h:40:0,
                 from openvdb/points/AttributeGroup.cc:33:
openvdb/points/AttributeArray.h:425:39: error: could not convert ‘0’ from ‘int’ to ‘tbb::atomic<unsigned int>’
     tbb::atomic<Index32> mOutOfCore = 0; // interpreted as bool
```

This PR addresses those and a couple of other such errors by substituting assignment for initialization of TBB atomics.

Anyone else run into this issue?

### CODE REVIEW

**Comment by Idclip** [comment]
Not run into this, but could this also be solved by doing `tbb::atomic<Index32> mOutOfCore = Index32(0);`

**Comment by pcucka** [comment]
No, the problem is not the sign conversion, it's the absence (by design) of a `tbb::atomic<T>::atomic(T)` constructor.

**Comment by danrbailey** [comment]
@pcucka - I haven't run into this issue, but I note that the James Reinders TBB book says:

"You can rely on zero initialization to initialize an atomic to 0. To create an atomic with a specific value, default-construct it first, and afterword assign a value to it."

So in fact, for numeric atomics, class member variables and C++11, I think it's not necessary to assign the zero value at all, we can just switch this to use the default constructor?

**Comment by pcucka** [comment]
For non-static data members, zero-assignment can be omitted only if the member is listed explicitly in the class constructor's initializer list.  So, for example, these are equivalent:
```
AttributeArray(): mPageHandle() { mOutOfCore = 0; }  // A

AttributeArray(): mPageHandle(), mOutOfCore() {}  // B
```
but
```
AttributeArray(): mPageHandle() {}  // C
```
would leave `mOutOfCore` uninitialized.

I have a slight preference for assignment in this case, since it makes it clear that the initial value is zero, but I'm OK with either A or B.

**Comment by danrbailey** [comment]
> For non-static data members, zero-assignment can be omitted only if the member is listed explicitly in the class constructor's initializer list. So, for example, these are equivalent:
> 
> ```
> AttributeArray(): mPageHandle() { mOutOfCore = 0; }  // A
> 
> AttributeArray(): mPageHandle(), mOutOfCore() {}  // B
> ```
> but
> 
> ```
> AttributeArray(): mPageHandle() {}  // C
> ```
> would leave `mOutOfCore` uninitialized.
> 
> I have a slight preference for assignment in this case, since it makes it clear that the initial value is zero, but I'm OK with either A or B.

That's fair, I'm ok with the explicit way of doing it.

**Pull request merged**
