### PR TITLE
Fix C++20 compatibility by removing deprecated shared_ptr::unique()

### LINKED ISSUE #1590: C++20 compatibility
The following line:
https://github.com/AcademySoftwareFoundation/openvdb/blob/7edd8cd86f105a01a41ad7b2bf59a81034cd79fb/openvdb/openvdb/points/AttributeSet.cc#L283
is not compiling for me on C++20 with MSVC 19.28.29916.0, due to [std::shared_ptr<>::unique()](https://en.cppreference.com/w/cpp/memory/shared_ptr/unique) being deprecated and removed in C++20.

### PR DESCRIPTION
**Pull request by jdumas**
Fix #1590.

### CODE REVIEW

**Comment by jdumas** [comment]
It seems the CI failed due to a transient network issue with vcpkg? Can a maintainer rerun the failed workflow?

**Review by Idclip — APPROVED** [review]
lgtm, thanks @jdumas (@danrbailey might be worth adding a release note for C++20 conformance with MSVC)

**Comment by jdumas** [comment]
I'm a bit puzzled by the CI issue. Seems like a network issue but it occurred twice on the same Windows job. It's been a while though so could we try to rerun it again?

**Comment by jdumas** [comment]
Hi there. Can we merge this?

**Comment by Idclip** [comment]
> I'm a bit puzzled by the CI issue. Seems like a network issue but it occurred twice on the same Windows job. It's been a while though so could we try to rerun it again?

Yeah we can ignore this failure

> Hi there. Can we merge this?

Needs two maintainer approvals. @danrbailey

**Review by danrbailey — APPROVED** [review]

**Pull request merged**
