### PR TITLE
Fix for potential crash when reading invalid .vdb files.

### PR DESCRIPTION
**Pull request by jmlait**
Original fix thanks to Matthias Ueberheide.

### CODE REVIEW

**Review by kmuseth — APPROVED** [review]
Looks good to me (just initialization of variable and moving an error check forward)

**Comment by kmuseth** [comment]
weird, one of the nanovdb unit-tests failed on Windows because it timed out! Never seen that error before ... @jmlait  can you re-run that test?

**Comment by Idclip** [comment]
Looks like it segfaulted, it didn't time out

**Comment by kmuseth** [comment]
re-ran the test and it passed so it might have been a resource issue, like insufficient memory

**Comment by Idclip** [comment]
As far as I know your `nanovdb_openvdb_unit_test` target doens't use any VDB IO anyway? So that crash was probably not related to this change. 

I'd keep an eye out if it happens again in case it's a non-deterministic issue with the latest nanovdb changes

**Comment by jmlait** [comment]
Built 10.1 with this version and ran sop-based reg tests on it with no change in behaviour from before the change.

**Pull request merged**
