### PR TITLE
Merge feature/inlinehalf

### PR DESCRIPTION
**Pull request by Idclip**

### CODE REVIEW

**Comment by Idclip** [comment]
@danrbailey githib won't let me interactively resolve conflicts because "feature/inlinehalf branch is a protected branch". I also can't merge master->feature/inlinehalf for the same reason. So I've had to create *another* branch which merges master->feature/inlinehalf and then PR that... can we change this setting?

**Comment by Idclip** [comment]
I've resolve this for this case by doing the above (opening a new PR with master->feature/inline and merging that)

**Comment by danrbailey** [comment]
> I've resolved this for this case by doing the above (opening a new PR with master->feature/inline and merging that)

I've enabled "Allow force pushes" on feature branches, but that may not fix it because I suspect this might be caused by the DCO check. We'll have to test it.

**Comment by danrbailey** [comment]
Just added a CI check into this feature branch for the USE_IMATH_HALF variable:

https://github.com/AcademySoftwareFoundation/openvdb/pull/966

**Review by jmlait — APPROVED** [review]

**Review by danrbailey — APPROVED** [review]

**Pull request merged**
