### PR TITLE
Fix SOP OpenVDB Extrapolate: expand SDF narrow band with dilate value…

### PR DESCRIPTION
**Pull request by apradhana**
Cherry-pick SOP Extrapolate to do no operation when dilation value less than 1.

### CODE REVIEW

**Comment by danrbailey** [comment]
Hi Andre, if you update this branch by merging in master, it should pass the CI. I recently bumped the cache key to v4 and I believe v3 has been evicted now.

**Comment by apradhana** [comment]
@danrbailey : if I merge-in master, won't that incorporate all the changes in master to this branch, including NanoVDB? I think we don't want that to be included in the v8.2 release, correct?

**Comment by danrbailey** [comment]
> @danrbailey : if I merge-in master, won't that incorporate all the changes in master to this branch, including NanoVDB? I think we don't want that to be included in the v8.2 release, correct?

Oh I hadn't spotted you were trying to merge this to v8.2. Just realized I missed a change from master so that it re-saves the Houdini cache as an empty dummy cache so added that here - #1256.

I've then taken all the cache related changes and applied them in a new PR that's targeted towards the v8.2 branch - #1257. We're in a bit of a transition phase, but I think this is the minimum needed to build this branch against the weekly Houdini caches.

**Comment by danrbailey** [comment]
> > @danrbailey : if I merge-in master, won't that incorporate all the changes in master to this branch, including NanoVDB? I think we don't want that to be included in the v8.2 release, correct?
> 
> Oh I hadn't spotted you were trying to merge this to v8.2. Just realized I missed a change from master so that it re-saves the Houdini cache as an empty dummy cache so added that here - #1256.
> 
> I've then taken all the cache related changes and applied them in a new PR that's targeted towards the v8.2 branch - #1257. We're in a bit of a transition phase, but I think this is the minimum needed to build this branch against the weekly Houdini caches.

I merged that PR now, so you should be able to update this one by merging in the v8.2 branch and then the CI will pass.

**Review by danrbailey — APPROVED** [review]

**Pull request merged**
