### PR TITLE
Add more counting tools

### PR DESCRIPTION
**Pull request by danrbailey**
Adding:

* tools::countActiveLeafVoxels() [+bbox version]
* tools::countInactiveVoxels()
* tools::countInactiveLeafVoxels()
* tools::countActiveTiles()

and changed the Tree methods to use these tools.

### CODE REVIEW

**Comment by danrbailey** [comment]
@Idclip - I keep getting a couple of failures in the AX jobs with this PR. It seems to be the two g++ AX jobs that fail but with no actual error as far as I can tell. Did you see this before?

**Comment by Idclip** [comment]
@danrbailey no idea, I've just kicked the jobs off again. I've even tried running the github cli tool `gh` to download the logs but they don't exist. Will see if it happens again

**Comment by Idclip** [comment]
CI looks fine now

**Comment by danrbailey** [comment]
> ~CI looks fine now~ spoke too soon. I have no idea why those jobs are failing, impossible to tell when the logs vanish...

It's weird, might try and close out this PR and create a new one. It doesn't seem like other PRs are having this problem.

**Pull request closed without merging**
