### PR TITLE
Added code coverage with website deployment

### PR DESCRIPTION
**Pull request by Idclip**
Signed-off-by: Nick Avramoussis <4256455+Idclip@users.noreply.github.com>

### Summary

This PR adds CI support for gcov with automatic publishing to gh-pages. Here's what it looks like on my fork:

code coverage: https://idclip.github.io/openvdb/code_coverage/index.html
landing page:    https://idclip.github.io/openvdb/docs/index.html (Link to code coverage at the bottom

### Notes

 - performance: gcov takes a long, long time. I had to enable -01 optimisations to get past GHA 6hour limits. This means that the coverage branch stats are pretty skewed. However the line information alone is worth having.
 - I changed the sanitizers to run twice a month (1st, 15th) rather than once a week.
 - The coverage CI automatically updates the `gh-page` every time its run
 
### Important

This PR changes the way the docs are deployed. Previously the doxygen docs would be deployed to ROOT. Now they are deployed to the `gh-pages` branch in a subdirectory:

`./docs/`  this folder is targeted by the docs workflow. Anything in here is deleted and replaced on exec of the docs.yml
`./code_coverage/`  this folder is targeted by the gcov workflow. Anything in here is deleted and replaced on exec of the sanitizers.yml

This means there is no landing page in the root of the `gh-pages` branch. Once this PR is merged, the following needs to be done:

 1) delete the contents of the `gh-pages` branch
 2) Re-run the docs.yml and sanitizers.yml to publish to the above folders.
 3) Add the following index.html to the root of the `gh-pages` branch.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv=Refresh content="0;url=docs/index.html"></head></html>
```

This was the nicest way I could come up with with allowing two workflows to publish "components" of the github page website.

### CODE REVIEW

**Comment by Idclip** [comment]
You can ignore the mac build failures. They are addressed by this PR https://github.com/AcademySoftwareFoundation/openvdb/pull/1070

**Review by danrbailey — APPROVED** [review]

**Comment by Idclip** [comment]
@danrbailey I'd like to fix the documentation deployment to the vdb website. It's still a bit broken: https://www.openvdb.org/documentation/doxygen/index.html

This PR adds the coverage docs, but also changes the doc job to deploy to the `openvdb-website` repo! it does however need a deployment key: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository

Ultimately I think we should remove the gh-pages from this repo and migrate back to the website. But it would be easier to discuss in a meeting. Let me know what you think.

**Comment by danrbailey** [comment]
I've taken another look at this and none of this makes any sense to me. I remember spending quite a while trying to get this working last time and getting nowhere, but I don't remember enough of the details to not have to start over from scratch with this. @idclip - If you have the knowledge and the motivation to go through this process, I think it's best we just request you get admin access so you can experiment with adding these deploy keys.

**Comment by Idclip** [comment]
Closing this, opening a new PR https://github.com/AcademySoftwareFoundation/openvdb/pull/1441 which incorporates these changes

**Pull request closed without merging**
