### PR TITLE
Update RE-LICENSE_NOTE.txt

### PR DESCRIPTION
**Pull request by melsdneg**

### CODE REVIEW

**Comment by melsdneg** [comment]
I have signed into the EasyCLA several time but my commits still show as missing auth. Please advise.

**Comment by dgovil** [comment]
@jmertic might have some suggestions, but he usually recommends filing a ticket here: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/create/143

The only other things I can think of is that your email is signed with capital DNEG instead of lowercase DNEG? 

Apologies for the hassle!

**Comment by jmertic** [comment]
Hi @melsdneg - who should be managing DNEG's CCLA? Henry Vera is listed but I believe he is no longer with DNEG, correct?

**Comment by melsdneg** [comment]
Hi John and Dhruv,

I was informed that anyone with a dneg email address can sign in to EasyCLA
which I can do. Unfortunately I am unable to authorize my PR. My order of
events doesnt seem to register with the github PR process or something
along those lines. Can I schedule a quick call with someone to go over my
steps and sort this out?

Thank you again for your support.

Best,
Sam

**Comment by dgovil** [comment]
Sent you an email. Happy to jump on whenever :-) I think I have some ideas

**Comment by jmertic** [comment]
Please file a ticket at https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/create/143 for this @melsdneg - they can debug and see what the issue is

**Review by apradhana — APPROVED** [review]

**Comment by jmertic** [comment]
Seems like the CLA checks are Green now - good to merge in?

**Comment by dgovil** [comment]
Yep, just need someone else from the TSC to give a second approval I
believe for it to be mergable.

I’ll email the group and see if they can get these merged in asap.

**Review by kmuseth — APPROVED** [review]

**Pull request merged**
