### PR TITLE
Change MPL License to Apache 2.0

### PR DESCRIPTION
**Pull request by dgovil**
This PR changes the MPL 2.0 license to Apache 2.0 as discussed. 
However, we should wait to merge this in till the following things are completed:

- [X] ILM signs off (@danrbailey to follow up)
- [X] TSC has chosen the new ASWF Standard CLA
- [X] @kmuseth said we should wait till some of the NanoVDB PRs are merged in.

I'm putting this PR up now so that I can get my own CLA squared away , and in case people want to see if I missed anything since it's a very large PR by file count.

The new CLA links:
ICLA - https://cla-signature-files-prod.s3.amazonaws.com/contract-group/28a0d3d8-b869-44e0-a4f4-06b50c49822f/template/icla-2024-09-04T09-58-58Z.pdf
CCLA - https://cla-signature-files-prod.s3.amazonaws.com/contract-group/28a0d3d8-b869-44e0-a4f4-06b50c49822f/template/ccla-2024-09-04T09-58-59Z.pdf

The link to pre-sign the CCLA https://organization.lfx.linuxfoundation.org/foundation/a092M00001If9vIQAR/project/lfPSOFZmSa0ojY6q7v/cla

### CODE REVIEW

**Comment by kmuseth** [comment]
I believe we have signify from everyone now. @dgovil are you going to create a PR with Apache v2 in the headers?

**Comment by dgovil** [comment]
@kmuseth  oh great news. Yes this should have all your nano VDB changes. 

I can do another pass after I'm back on the 5th of August but everything should be done here afaik. 

Cc @jmertic who can change the CLA once this PR is merged in. 

I can do a follow up PR once I'm back in case there's anything I missed, but I don't believe there are any new files since then.

**Comment by jmertic** [comment]
I can make the CLA and Technical Charter changes whenever everyone is ready, provided the TSC has approved both.  Let me know.

**Comment by dgovil** [comment]
Awesome. In that case, I think either order makes sense. 

If the TSC wants to merge this PR, and then change the CLA after, you don't need to wait for my return for anything. 

Otherwise if the CLA changes first, I'll have to re-sign the CLA which I'll only be able to do on the 5th. In that case, I can also update the CLA copies in the repo with the correct language as well. 

Either way works. I'll do any follow up work as needed when I return. 

Thank you all so much!

**Comment by jmertic** [comment]
@kmuseth - As TSC Chair, it's your call. Let me know.

**Review by kmuseth — APPROVED** [review]
thanks

**Comment by kmuseth** [comment]
it looks like the DCO signoff failed. I cannot merge before it;s fixed

**Comment by jmertic** [comment]
We need to not merge this in until we are ready to switch over the CLA. We should be read to have the pre-signing tomorrow or Thursday at the latest. Thanks!

**Comment by dgovil** [comment]
@danrbailey I've now added the links to the CLA text (both ICLA and CCLA) to the PR description. I've also added the link to pre-sign the CCLA as well.

**Review by apradhana — APPROVED** [review]

**Comment by danrbailey** [comment]
Merging to `feature/apache2` branch. Once the CI is passing, we will create a new MR to merge to master once again.

**Comment by dgovil** [comment]
Awesome. Thank you!

**Pull request merged**
