### PR TITLE
Fix Unit Test Failures with Blosc >= 1.19

### PR DESCRIPTION
**Pull request by danrbailey**

### CODE REVIEW

**Comment by Idclip** [comment]
There's a test in `weekly.yml` which tests blosc versions - might be worth adding 1.19/1.20/1.21 there!

**Comment by danrbailey** [comment]
> There's a test in `weekly.yml` which tests blosc versions - might be worth adding 1.19.0/1.20.0/1.21.0 there!

Good idea, mind if we do that as a separate PR?

**Review by jmlait — APPROVED** [review]

**Comment by Idclip** [comment]
> > There's a test in `weekly.yml` which tests blosc versions - might be worth adding 1.19.0/1.20.0/1.21.0 there!
> 
> Good idea, mind if we do that as a separate PR?

Sounds like we should add this now if there are concerns with 1.21?

**Comment by danrbailey** [comment]
> > > There's a test in `weekly.yml` which tests blosc versions - might be worth adding 1.19.0/1.20.0/1.21.0 there!
> > 
> > 
> > Good idea, mind if we do that as a separate PR?
> 
> Sounds like we should add this now if there are concerns with 1.21?

Yeah, sounds good. I'll merge this now.

**Pull request merged**
