### PR TITLE
Add Houdini 17.5 to weekly build and update schedule day to Sunday

### PR DESCRIPTION
**Pull request by danrbailey**
Once we have a successful Houdini install in the cache, I'll update the CI jobs for 17.5.

### CODE REVIEW

**Comment by Idclip** [comment]
@danrbailey are you also seeing builds stalling? https://github.com/AcademySoftwareFoundation/openvdb/runs/905319110 Seems this didn't fully pass?

**Comment by danrbailey** [comment]
> @danrbailey are you also seeing builds stalling? https://github.com/AcademySoftwareFoundation/openvdb/runs/905319110 Seems this didn't fully pass?

Yeah, I didn't wait for all the builds to succeed because this doesn't touch anything in the codebase or the CI jobs for the regular builds. If GHA had an official "skip-ci" tag I could have added to the PR or commit message, I'd have used that. You may disagree, but I think it's reasonable to use our discretion in these types of cases. For peace of mind, here's the successful build on master:

https://github.com/AcademySoftwareFoundation/openvdb/runs/907325375

**Comment by Idclip** [comment]
Okay... my main point this is that this is happening consistently.
https://github.com/AcademySoftwareFoundation/openvdb/pull/764
https://github.com/AcademySoftwareFoundation/openvdb/pull/758

I do disagree

**Comment by danrbailey** [comment]
> Okay... my main point this is that this is happening consistently.
> #764
> #758
> 
> I do disagree

There are a few threads on the GitHub Actions forums about these type of issues. It might be related to usage limits kicking in - we can keep an eye on it and hopefully stability will improve.

**Pull request merged**
