### PR TITLE
OVDB-45: Collapse houdini/ and maya/ subdirectories

### PR DESCRIPTION
**Pull request by pcucka**
This eliminates the unnecessary `openvdb_houdini/houdini/` and `openvdb_maya/maya/` subdirectories by merging their contents into their respective parent directories.

### CODE REVIEW

**Comment by danrbailey** [comment]
@pcucka - this didn't build the Circle check. Can you unfollow your personal fork of OpenVDB in your personal CircleCI account and then push an empty commit to trigger a new build please?

**Comment by pcucka** [comment]
I'm planning to merge this today.  Please let me know ASAP if you want me to wait.

**Comment by danrbailey** [comment]
> I'm planning to merge this today. Please let me know ASAP if you want me to wait.

I just tried to combine your change here and #404 (which touches every single SOP) and git was smart enough to handle it without conflicts. Sounds good to me. :+1:

**Comment by pcucka** [comment]
Thanks for confirming that!  Hopefully this won't be disruptive for anyone.

**Pull request merged**
