### PR TITLE
Run CI against VFX Ref 2018

### PR DESCRIPTION
**Pull request by danrbailey**
Although we don't officially support VFX Reference 2018, our codebase seems to still build against it, so I suggest we keep this test for the time being. When we deprecate support for Houdini 18.0 later this year, we can jump to VFX Reference 2020 as our minimum supported version - which will make Boost 1.70 our minimum version.

### CODE REVIEW

**Review by jmlait — APPROVED** [review]

**Review by Idclip — CHANGES_REQUESTED** [review]
The whole point of the boost change was so you can have `disable_checks` OFF for H18... your previous builds were failing due to the older CMake version so you should be able to revert that change?

**Comment by danrbailey** [comment]
> The whole point of the boost change was so you can have `disable_checks` OFF for H18... your previous builds were failing due to the older CMake version so you should be able to revert that change?

My untested assumption was that there were other old deps in VFX 2018 that would require disabling checks, such as TBB 2017. I'll revert this change and see if it still passes.

**Comment by danrbailey** [comment]
> > The whole point of the boost change was so you can have `disable_checks` OFF for H18... your previous builds were failing due to the older CMake version so you should be able to revert that change?
> 
> My untested assumption was that there were other old deps in VFX 2018 that would require disabling checks, such as TBB 2017. I'll revert this change and see if it still passes.

Nope, failed on attempting to pull in TBB 2017. Un-re-reverted.

**Comment by Idclip** [comment]
> Nope, failed on attempting to pull in TBB 2017. Un-re-reverted.

Oh I misunderstood what you are doing - I thought it would be better to explicitly tell our CMake to build against Houdini 18 boost on the VFX19 platform. But this is okay too.

**Review by Idclip — APPROVED** [review]

**Pull request merged**
