### PR TITLE
Fixed crash in PagedArray unit test

### PR DESCRIPTION
**Pull request by kmuseth**
Signed-off-by: Ken Museth <ken.museth@gmail.com>

Fixed crash in unittest of PagedArray

### CODE REVIEW

**Comment by kmuseth** [comment]
There seems to be something wrong with the macOS 1015 CI!?

**Comment by Idclip** [comment]
> There seems to be something wrong with the macOS 1015 CI!?

Should be fixed with this PR https://github.com/AcademySoftwareFoundation/openvdb/pull/859

**Review by danrbailey — APPROVED** [review]

**Comment by kmuseth** [comment]
@Idclip Please pull the latest version of this branch and verify that the crash is gone on your end (it obviously is on mine)

**Review by Idclip — APPROVED** [review]

**Comment by Idclip** [comment]
Crash has gone! May want to update the docs here https://github.com/AcademySoftwareFoundation/openvdb/pull/858/files#diff-6562d797592efa181821826ad857a83ebda9dcd6dfd5cdfdd606fcbde39b2d71R37

**Comment by kmuseth** [comment]
updated doxygen and removed any reference to PagedArray::push_back

**Pull request merged**
