### PR TITLE
Replace boost conversion_traits with std::common_type

### PR DESCRIPTION
**Pull request by Idclip**
Re-creating this so that we don't lose visibility on it. It currently cannot be merged due to https://github.com/AcademySoftwareFoundation/openvdb/issues/1700

### CODE REVIEW

**Comment by bpmckinnon** [comment]
One possible option given that std::numeric_limits is overridden is to try using std::numeric_limits<T>::is_specialized instead.
https://en.cppreference.com/w/cpp/types/numeric_limits/is_specialized

**Comment by bpmckinnon** [comment]
I've verified that this is at least a potential option on my windows build... but I can't guarantee it will work in the build environment that is failing.

**Comment by apradhana** [comment]
As for the problem that Matthew raised in [Issue 1700 ](https://github.com/AcademySoftwareFoundation/openvdb/issues/1700), I have a fix that I included in the [draft PR for supporting half grid](https://github.com/AcademySoftwareFoundation/openvdb/pull/1730). What's needed is adding a `cwiseAdd` specialization for `Vec3<math::half>` as shown [here](https://github.com/apradhana/openvdb/blob/half_grid_support/openvdb/openvdb/Types.h#L715-L730).

**Comment by bpmckinnon** [comment]
Has there been any update on the cwiseAdd function?  Otherwise I can add the is_specialized change I proposed.

**Comment by bpmckinnon** [comment]
Before this change can be resubmitted std::is_arithmetic_v should be replaced with std::numeric_limits::is_specialized to prevent the initial issue that was flagged

**Review by kmuseth — APPROVED** [review]

**Comment by danrbailey** [comment]
Merging to a feature branch to bring this PR up-to-date before merging to master.

**Pull request merged**
