### PR TITLE
CI - Blosc & ABI checks

### PR DESCRIPTION
**Pull request by Idclip**
- Added blosc CI for 1.19, 1.20 and 1.21
 - Added ABI CI for VDB major versions
 
I added a new virtual method and a new `int` member to `Grid`. Here's an example of the ABI run and subsquent report: https://github.com/Idclip/openvdb/actions/runs/2234898611

image

### CODE REVIEW

**Review by danrbailey — APPROVED** [review]
Looks good to me. Would it be possible to add a link to that report to the `README.md` too so it shows up alongside all the other CI badges?

**Comment by Idclip** [comment]
> Looks good to me. Would it be possible to add a link to that report to the `README.md` too so it shows up alongside all the other CI badges?

I think the badges can only be created per workflow not per job - so I'd have to split this out into a separate `abi_compliance.yml`

**Comment by danrbailey** [comment]
> > Looks good to me. Would it be possible to add a link to that report to the `README.md` too so it shows up alongside all the other CI badges?
> 
> I think the badges can only be created per workflow not per job - so I'd have to split this out into a separate `abi_compliance.yml`

Not a deal-breaker. Also, a quick mention that there's also this simple ABI check that I added a while back:

https://github.com/AcademySoftwareFoundation/openvdb/tree/master/openvdb_houdini/openvdb_houdini/abitest

**Comment by Idclip** [comment]
@danrbailey is that a go ahead? Would you like me to move these into their own workflow? Happy to do so.

**Comment by danrbailey** [comment]
> @danrbailey is that a go ahead? Would you like me to move these into their own workflow? Happy to do so.

No, that's ok, go ahead. Just if it was easy to make it show up as a badge.

**Pull request merged**
