### PR TITLE
Fixed a range bug in LevelSetSphere

### PR DESCRIPTION
**Pull request by kmuseth**
Signed-off-by: Ken <ken.museth@gmail.com>

### CODE REVIEW

**Comment by Idclip** [comment]
@kmuseth could you also update the root `CMakeLists.txt` (~line 55) file to:

`
set(OpenVDB_MAJOR_VERSION 9)
set(OpenVDB_MINOR_VERSION 0)
set(OpenVDB_PATCH_VERSION 1)
`

This will bump the .so/version.h version numbers

**Comment by kmuseth** [comment]
> @kmuseth could you also update the root `CMakeLists.txt` (~line 55) file to:
> 
> ```
> set(OpenVDB_MAJOR_VERSION 9)
> set(OpenVDB_MINOR_VERSION 0)
> set(OpenVDB_PATCH_VERSION 1)
> ```
> 
> This will bump the .so/version.h version numbers

@Idclip  I see you created a separate PR with that change. I approved it so can you approve this PR as well

**Review by Idclip — APPROVED** [review]

**Comment by Idclip** [comment]
Done! Yeah just wanted to make sure we had bumped the lib version before any changes

**Comment by kmuseth** [comment]
> Done! Yeah just wanted to make sure we had bumped the lib version before any changes

great, thanks @Idclip

**Pull request merged**
