### PR TITLE
Replace boost::any with std::any

### PR DESCRIPTION
**Pull request by bpmckinnon**
Replace BOOST_STATIC_ASSERT with static_assert

### CODE REVIEW

**Review by Idclip — APPROVED** [review]

**Comment by Idclip** [comment]
Thanks a lot @bpmckinnon! I actually tried to fix this years ago with our metadata implementation (linking just for future reference https://github.com/AcademySoftwareFoundation/openvdb/pull/744) but happy to accept this change instead. 

Do you think you can sign off your commits and fill out the CLA?

I think you're right in that all that's left is the conversion_traits header (and it would be nice to have our own iostream/interprocess impl), we can look to solve that too.

**Comment by bpmckinnon** [comment]
I'm working on the CLA.  I was doing this as part of work, so I'm looking for a corporate manager for the CLA.

**Comment by Idclip** [comment]
> I'm working on the CLA. I was doing this as part of work, so I'm looking for a corporate manager for the CLA.

No worries, keep us posted - we can contribute these changes on your behalf but would be nicer if you're able to get it signed

**Comment by bpmckinnon** [comment]
Alright, this should be ready to go

**Review by danrbailey — APPROVED** [review]

**Pull request merged**
