### PR TITLE
Add Mac OS 11 CI

### PR DESCRIPTION
**Pull request by danrbailey**

### CODE REVIEW

**Comment by Idclip** [comment]
We already have a `macos-latest` test in `weekly.yml`

**Comment by Idclip** [comment]
Ah turns out:

> The macos-latest label currently uses the macOS 10.15 runner image.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

maybe we should just switch that one to 11

**Comment by danrbailey** [comment]
> https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

Yes, but think it perhaps makes sense to use the explicit versions instead of latest so our CI doesn't quietly change underneath us.

**Comment by Idclip** [comment]
That's what I suggested we do.

**Comment by danrbailey** [comment]
@Idclip - so should we have both 10.15 and 11.0 in the weekly?

**Comment by Idclip** [comment]
Nah I think we just change this to 11, the other is already tested elsewhere if I remember correctly

**Comment by danrbailey** [comment]
> Nah I think we just change this to 11, the other is already tested elsewhere if I remember correctly

Ok, I've updated this branch to change `macos-latest` to `macos-11` for all the mac CI jobs and added a `macos-1015` job to the weekly build as with these other changes, only the AX build was running on 10.15.

**Review by Idclip — APPROVED** [review]

**Pull request merged**
