### PR TITLE
Fixed documentation install path

### PR DESCRIPTION
**Pull request by Idclip**
Signed-off-by: Nick Avramoussis <4256455+Idclip@users.noreply.github.com>

### CODE REVIEW

**Review by danrbailey — APPROVED** [review]
Looks good, thanks. I can update my PR after this goes in.

**Comment by danrbailey** [comment]
I realize this is such a minor change, I just rolled this into my documentation PR - #944

**Comment by Idclip** [comment]
@danrbailey Thanks! I would prefer though that, where possible, we merge PRs that don't require any changes i.e. this->master->your branch.

**Comment by danrbailey** [comment]
> @danrbailey Thanks! I would prefer though that, where possible, we merge PRs that don't require any changes i.e. this->master->your branch.

Yes, I agree. I would prefer that we use pendingchanges instead of modifying the change notes directly. In this case, I brought the few lines across myself to avoid having to resolve any conflicts.

**Pull request closed without merging**
