### PR TITLE
Fix minor documentation typo

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
Changes from `simular` to `similar`

### CODE REVIEW

**Review by danrbailey — APPROVED** [review]

**Comment by danrbailey** [comment]
Looks good, thanks!

**Comment by mehmetoguzderin** [comment]
Thank you for maintaining this fantastic effort!

**Review by jmlait — APPROVED** [review]

**Comment by kmuseth** [comment]
fixed already but thanks!

**Comment by mehmetoguzderin** [comment]
@kmuseth sure 😹

**Pull request closed without merging**
