### PR TITLE
Exposed TypeLists of the default set of OpenVDB types

### PR DESCRIPTION
**Pull request by Idclip**
Signed-off-by: Nick Avramoussis <4256455+Idclip@users.noreply.github.com>

Due to interest in the last TSC, I've split this out into a more complete and isolated PR. Thoughts welcome

### CODE REVIEW

**Comment by Idclip** [comment]
@jmlait @danrbailey @kmuseth @apradhana @richhones

**Comment by Idclip** [comment]
As discussed in the TSC, will remove the `Native` prefix and merge after next TSC

**Review by danrbailey — APPROVED** [review]
This is awesome, thanks Nick!

Only minor thing is that I think it's (a little) less clear how to register custom grid types now. It's not obvious to me whether people should append to `GridTypes` or whether they should instead follow the example of StringGrid and do `StringGrid::registerGrid()` in `openvdb::initialize()`. I know there are users already adding custom grid types which will likely trigger conflicts when attempting to update after this change, so perhaps some comments to explain what to do in `openvdb::initialize()` would help?

**Comment by danrbailey** [comment]
To summarize the different categories in use (I dropped "grid", "tree" and "types" from these to make the differences clearer):

TypeList:

```
Float = [Float, Double]
Integer = [Int32, Int64]
Scalar = [Float, Double, Int32, Int64]
Vec3 = [Vec3I, Vec3S, Vec3D]
 = [Mask, Bool, Float, Double, Int32, Int64, Vec3I, Vec3S, Vec3D, PointIndex, PointData]
```

Explicit Instantiation:

```
Real = [Float, Double]
Numeric = [Float, Double, Int32, Int64]
Vec3 = [Vec3I, Vec3S, Vec3D]
Volume = [Bool, Float, Double, Int32, Int64, Vec3I, Vec3S, Vec3D]
All = [Mask, Bool, Float, Double, Int32, Int64, Vec3I, Vec3S, Vec3D, PointIndex, PointData]
```

Houdini:

```
Real = [Float, Double]
Scalar = [Float, Double, Int32, Int64]
Vec3 = [Vec3I, Vec3S, Vec3D]
Point = [PointIndex, PointData]]
Topology = [Bool, Float, Double, Int32, Int64, Vec3I, Vec3S, Vec3D]
 = [Float, Double, Int32, Int64, Vec3I, Vec3S, Vec3D]
```

**Comment by Idclip** [comment]
Thanks @danrbailey! Are you advocating I change the categories here? I'm not sure what would be better. In Houdini's (or other applications) cases though, I would expect them to reconstruct their own TypeLists based on their custom requirements. For example, in the houdini plugin, I would expect to see something like:

```
using HoudiniTopologyGridTypes =
   openvdb::ScalarGridTypes::
      Append<openvdb::Vec3GridTypes>::
      Append<openvdb::BoolGrid>;
```

Rather than us arbitrarily defining this.

**Comment by danrbailey** [comment]
> Thanks @danrbailey! Are you advocating I change the categories here? I'm not sure what would be better. In Houdini's (or other applications) cases though, I would expect them to reconstruct their own TypeLists based on their custom requirements. For example, in the houdini plugin, I would expect to see something like:
> 
> ```
> using HoudiniTopologyGridTypes =
>    openvdb::ScalarGridTypes::
>       Append<openvdb::Vec3GridTypes>::
>       Append<openvdb::BoolGrid>;
> ```
> 
> Rather than us arbitrarily defining this.

Houdini has more baggage because it's evolved from an older point in time and is probably least important of the three be in sync, but it's still useful to see quite how different each of these categories are though.

My proposal is to change this in your categories:

Float -> Real
Scalar -> Numeric

Then add any new ones as and when we need them in the future (volume, point, etc).

**Comment by Idclip** [comment]
Think I prefer Scalar to Numeric but don't feel strongly about it - I will make this change

**Comment by Idclip** [comment]
I also applied `Real` and `Numeric` to the Attribute list counteparts for VDB Points

**Pull request merged**
