### PR TITLE
Makefile enhancements

### PR DESCRIPTION
**Pull request by davvid**
Make the build more configurable.
Follow the commonly-accepted meaning of DESTDIR and prefix variables in the Makefile.

### CODE REVIEW

**Comment by MrMormon** [comment]
Uh, davvid?

**Comment by davvid** [comment]
Hello.  It looks like this branch has gone stale.  It's been a while since I've taken a look at this PR.

Would you like me to take a stab at rebasing and updating this series to the latest "master" branch?  I guess a better question is whether these changes are desired.

I'd like to kick these changes upstream because so that we don't have to tweak openvdb at $dayjob for build-related stuff.  If this is desirable then I can take another stab.

The only caveat is that this *will* change the semantics of the existing build setup.  IMO that is okay because the existing semantics are ad-hoc and non-standard, so using the "standard" GNU makefile variables, etc. will only help packagers in the future.

Let me know if I should rebase this branch.  If so I'll take a stab at it again when I get a chance.

**Comment by danrbailey** [comment]
I'm going to close this one out now this is pretty old and the focus is now on improving the CMake build. Thanks for the contribution nonetheless.

**Comment by davvid** [comment]
Sweet, I'll have a few updates coming for the cmake build instead.  Namely, start using `GNUInstallDirs` so that we can do `install(.... DESTINATION ${CMAKE_INSTALL_LIBDIR})` etc. in the various `install()` places.  cheers

**Pull request closed without merging**
