### PR TITLE
Fix Filter YZ Typo

### PR DESCRIPTION
**Pull request by danrbailey**
This PR builds on #383 which fixes the `doBoxY()`/`doBoxZ()` order in openvdb::tools::Filter, but additionally flips the order of the gaussian and mean filter implementations so that they use the previous XZY order to avoid breaking backwards-compatibility. I've added a comment to this effect as well.

The benefit here is that any new filters that get added can use the "correct" order without obfuscating the code, but the existing ones will continue to use the old ordering.

Note that `doBoxY()` and `doBoxZ()` are _private_ members so this doesn't change the public API.

### CODE REVIEW

**Comment by danrbailey** [comment]
@yuanming-hu - thanks a lot for the contribution and apologies it's taken so long for us to look at getting this merged. :)

**Comment by yuanming-hu** [comment]
No problem - super glad to make my humble contribution to this GREAT project!

**Comment by danrbailey** [comment]
> Why keep the x z y order instead of just doing x y z? As a separable filter it shouldn't make (much) of a difference - or have you observed that not to be the case?

Agreed, it doesn't make much of a difference, except that all existing computations and simulations will observe (tiny) floating-point differences. I think it's better that we keep the original order just to avoid introducing any change in behaviour, if the only real goal in doing so is a small readability improvement? (I attempted to address readability with a comment explaining the rationale behind the ordering).

**Comment by danrbailey** [comment]
> > Why keep the x z y order instead of just doing x y z? As a separable filter it shouldn't make (much) of a difference - or have you observed that not to be the case?
> 
> Agreed, it doesn't make much of a difference, except that all existing computations and simulations will observe (tiny) floating-point differences. I think it's better that we keep the original order just to avoid introducing any change in behaviour, if the only real goal in doing so is a small readability improvement? (I attempted to address readability with a comment explaining the rationale behind the ordering).

Going to merge this so that we don't delay further in adjusting our default branch. @kmuseth - happy to revisit this to discuss your comments further in a future TSC meeting.

**Pull request merged**
