### PR TITLE
Improve documentation of transforms

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
Fixes documentation of index to world or world to index space functions

### CODE REVIEW

**Review by kmuseth — APPROVED** [review]
Thanks - good catch

**Comment by mehmetoguzderin** [comment]
Thank you for building NanoVDB; it is excellent!

**Review by jmlait — APPROVED** [review]

**Review by kmuseth — COMMENTED** [review]
Thanks for these corrections - that have been added already in a separate commit that also includes other changes. Consequently I'll close this PR.

**Comment by kmuseth** [comment]
Thanks for these corrections - that have been added already in a separate commit that also includes other changes. Consequently I'll close this PR.

**Pull request closed without merging**
