### PR TITLE
RE-LICENSE_NOTE: add Walt Disney Animation Studios approval to relicense

### PR DESCRIPTION
**Pull request by davvid**

### CODE REVIEW

**Comment by davvid** [comment]
Heads-up @dgovil this was approved internally today so I've included both my sign-off and Nick's.

**Comment by dgovil** [comment]
That's awesome news. Thank you so much for the quick turnaround on it as well.

**Review by apradhana — APPROVED** [review]

**Comment by davvid** [comment]
I just amended the commit to use WDAS's legal name: "Walt Disney Pictures (Walt Disney Animation Studios)" per guidance from our legal department.

**Comment by dgovil** [comment]
Ah good catch. Thanks!

**Review by kmuseth — APPROVED** [review]

**Pull request merged**
