### PR TITLE
OVDB-53: Provide OP_Operator::getVersion override to return VDB version

### PR DESCRIPTION
**Pull request by danrbailey**
By introducing this override we need to be able to distinguish between the Houdini default (such as "17.5.204") and the VDB version (such as "6.2.0") in a syncNodeVersion() override.

I considered adding a prefix (such as "vdb:6.2.0") then settled on using the packed integer representation (such as "100794368"). Simply checking the string is non-empty and contains no "." characters is thus sufficient to determine this is a VDB version and not a Houdini version. I also couldn't think of any reason to need to preserve which version of Houdini this node was created in, in addition to which version of VDB was used. Native Houdini VDB nodes will still use the Houdini version.

Of course if there's any logic expecting the Houdini default form (X.Y.Z.W) then this will break, but I'm not aware of anything here.

### CODE REVIEW

**Comment by danrbailey** [comment]
@pcucka - any thoughts on this implementation?

**Comment by pcucka** [comment]
I'm waiting to hear @jmlait's thoughts, specifically on the intended use(s) of `getVersion` outside of `syncNodeVersion`.

**Comment by jmlait** [comment]
I'd think the vdb prefix would be cleaner, but have no objections to the packed version either.  All uses of these nodes in the future should get the vdb library version, not the houdini version, so match the behaviour of HDAs.  The packed version will certainly simplify people adding tests to the code.

**Comment by danrbailey** [comment]
> I'd think the vdb prefix would be cleaner, but have no objections to the packed version either. All uses of these nodes in the future should get the vdb library version, not the houdini version, so match the behaviour of HDAs. The packed version will certainly simplify people adding tests to the code.

I don't really mind either to be honest. If your preference is strong enough for vdb prefix, I'm happy to make the change? Otherwise if you want to approve this, I'll simply merge using the packed version.

**Comment by jmlait** [comment]
Whoever parses it has to parse a string anyways, so I think it is reasonable to have a vdb: prefix to parse out.  If it were an integer, a packed version is easier, but since it is a string there might as well be a helper function to do the comparison when we need it.

UT_String::compareVersionString can be used after the vdb: is skipped.

So put me down for vdb:6.1.0

**Comment by Idclip** [comment]
FWIW I agree with @jmlait. I've pulled these changes and am using them in AX with "vdb_ax:X.Y.Z" for a similar issue to the vdb points scatter stuff which started all of this. Works really well! +1

**Comment by pcucka** [comment]
Would it make sense to append "`vdbX.Y.Z`" (or whatever) to the string returned by the base class (i.e., `OP_Operator::getVersion`), so that we retain the Houdini version?

**Comment by danrbailey** [comment]
> Would it make sense to append "`vdbX.Y.Z`" (or whatever) to the string returned by the base class (i.e., `OP_Operator::getVersion`), so that we retain the Houdini version?

Can you perhaps give an example of what the Houdini version might be used for? I don't believe we've ever built a different version of a SOP for one version of Houdini as another.

**Comment by pcucka** [comment]
Well, we've never needed to call `syncNodeVersion` before either.  But an example (from the past) might be changing the default To Polygons output mode based on the existence of poly soups.

**Comment by danrbailey** [comment]
> Well, we've never needed to call `syncNodeVersion` before either. But an example (from the past) might be changing the default To Polygons output mode based on the existence of poly soups.

Right, I guess it doesn't cost much and it's a lot less effort to add it now than if we ever need it in the future.

As for the format, how about:

17.5.314:vdb6.2.0 ?

**Comment by pcucka** [comment]
It would be nice if the format were such that a base class `syncNodeVersion` (for example) could parse the Houdini version without needing to be aware of the VDB component.  It doesn't look like `UT_String::compareVersionString` allows that, though, at least not when the separator is either a space or a colon.

**Comment by danrbailey** [comment]
> It would be nice if the format were such that a base class `syncNodeVersion` (for example) could parse the Houdini version without needing to be aware of the VDB component. It doesn't look like `UT_String::compareVersionString` allows that, though, at least not when the separator is either a space or a colon.

@jmlait - I don't think the definition of compareVersionString is visible to us. Do you know if there's a way to achieve what @pcucka is suggesting here?

**Comment by danrbailey** [comment]
Bump - I need agreement on the version format to use to proceed here.

@jmlait @pcucka

**Pull request merged**
