### PR TITLE
RE-LICENSE_NOTE: add my relicensing note

### PR DESCRIPTION
**Pull request by davvid**

### CODE REVIEW

**Comment by davvid** [comment]
Heads-up @dgovil

**Comment by dgovil** [comment]
Awesome, thanks, David!

**Comment by davvid** [comment]
I thought I had already signed the CLA some time ago (I already have commits in this repo).

In any case, I opened a support ticket for the CLA: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-27276

cheers

**Comment by davvid** [comment]
Do we also need/want Walt Disney Animation Studios listed here? If so I can follow-up with Nick Cannon next week.

That'll take slightly longer since it'll require legal to sign off on it, but I can start pushing on that if it's needed.

**Comment by dgovil** [comment]
@davvid that would be great if we could get WDAS on there too just to cover our bases. @danrbailey is bringing it up on the ILM side, I'm not sure if y'all share any legal teams, but perhaps that'll help on the WDAS side as well. 

Thank you, and let me know if you need me to talk to Nick at all.

**Comment by davvid** [comment]
EasyCLA is passing so this should be good to merge now.

**Review by apradhana — APPROVED** [review]

**Review by jmlait — APPROVED** [review]

**Comment by dgovil** [comment]
Awesome. Thank you!

**Pull request merged**
